version: '3'

services:
  server:
    build: ./server
    command: python . -c config.yml
    volumes:
      - ./server:/app
    ports:
      - 8000:8000

  docs:
    build: ./docs
    command: make html
    volumes:
      - ./docs:/app
      - ./server:/app/server
